# Generated by Django 4.0.1 on 2022-01-29 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_permission_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ManyToManyField(to='app01.Role', verbose_name='角色'),
        ),
        migrations.AlterField(
            model_name='role',
            name='permission',
            field=models.ManyToManyField(to='app01.Permission', verbose_name='权限'),
        ),
    ]
