# Generated by Django 4.0.1 on 2022-01-29 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_alter_role_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissions',
            name='Permission_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_name',
            field=models.CharField(max_length=10),
        ),
    ]
