# Generated by Django 4.0.1 on 2022-01-29 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_alter_permissions_permission_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['id', 'name'], 'verbose_name': '图书', 'verbose_name_plural': '图书'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': '角色', 'verbose_name_plural': '角色'},
        ),
        migrations.RenameField(
            model_name='permissions',
            old_name='Permission_name',
            new_name='permission_name',
        ),
    ]
